name: VAL entorno

on:
  workflow_dispatch:

jobs:
  desplegar:
    name: Desplegar a producción
    runs-on: ubuntu-latest
    environment: produccion

    steps:
      - name: Simular un despliegue
        run: echo "Desplegando a producción..."
